Repository kokonior/C-Plus-Plus-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 Add hotel booking system
  HotelBookingSystem.cpp
Labels: hacktoberfest-accepted

#3 Update HotelBookingSystem.cpp
  HotelBookingSystem.cpp
Labels: enhancement, hacktoberfest-accepted

#2 added employee management project
  employeemanagement.cpp
Labels: enhancement, hacktoberfest-accepted

#4 Create Queue Array Using Cpp.cpp
  Queue Array Using Cpp.cpp
Labels: hacktoberfest-accepted, Create
